/**
 * Upload a file to Cloudflare R2 using a **Pre-Signed URL**.
 * This is the ultimate industry standard approach.
 * 
 * 1. It asks our safe Vercel backend (/api/get-upload-url) for a magic, temporary URL.
 * 2. It dumps the file into R2 using a basic PUT request to that magic URL.
 * 
 * Why this fixes your issues:
 * - NO Vercel 4.5MB size limits (the file goes directly to R2, bypassing Vercel).
 * - NO complex AWS Headers injected by the AWS SDK (which triggers aggressive CORS blocks).
 * - Secrets are 100% hidden on the backend.
 * 
 * @param {File} file - The file to upload
 * @param {string} folder - The folder prefix (e.g., 'avatars', 'posts')
 * @returns {Promise<string>} The public URL of the uploaded file
 */
export async function uploadToR2(file, folder = 'uploads') {
    try {
        const fileExt = file.name.split('.').pop();
        const fileName = `${folder}/${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExt}`;

        // 1. Ask Vercel backend for a Pre-Signed URL
        const presignRes = await fetch('/api/get-upload-url', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                fileName: fileName,
                contentType: file.type
            })
        });

        if (!presignRes.ok) {
            const err = await presignRes.json();
            throw new Error(`Failed to generate secure upload link: ${err.error || 'Unknown'}`);
        }

        const { uploadUrl, publicUrl } = await presignRes.json();

        // 2. Upload the file DIRECTLY to Cloudflare R2 using the Pre-Signed URL
        // NEVER pass 'Content-Type' or any custom headers here, or Cloudflare will immediately block it 
        // with CORS because it doesn't match the exact signature generated by AWS SDK.
        const uploadRes = await fetch(uploadUrl, {
            method: 'PUT',
            body: file
        });

        if (!uploadRes.ok) {
            throw new Error(`Cloudflare rejected the upload. Status: ${uploadRes.status}`);
        }

        // Return the final Cloudflare URL for this file
        return publicUrl;
    } catch (error) {
        console.error('Presigned R2 Upload Error:', error);
        throw new Error(error.message || 'Failed to upload image. Please try again.');
    }
}
